![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

![Formação Engenharia de Dados](https://d335luupugsy2.cloudfront.net/cms/files/524558/1707226566/$occu5m8t1op)

Este material tem como objetivo incentivar a prática dos conteúdos estudados até o momento, e a pesquisa. Tenha em consideração que o exercício foi pensado para incentivar a prática dos conteúdos estudados até então, porém aprender a pesquisar faz parte do processo de aprendizagem.

Fique tranquilo, faça os exercícios com calma, e boa prática!

#Orientações:

 - Faça uma copia deste arquivo
 - Após concluir os exercicios, suba seu exercicio para o GitHub e compartilhe o link no **google** Classroom

#Exercícios

#Funções

Escreva uma função chamada soma que recebe dois números como parâmetros e retorna a soma deles

In [10]:
def soma(num1, num2):
    resultado = f"A soma dos dois números é {num1 + num2}."
    return resultado

soma(1, 2)

'A soma dos dois números é 3.'

Escreva uma função chamada verificar_paridade que recebe um número como parâmetro e retorna True se for par e False se for ímpar.

In [11]:
def verificar_paridade(numero):
  if numero % 2 == 0:  
    return True
  else:
    return False

verificar_paridade(3)

False

Escreva uma função chamada verificar_palindromo que recebe uma string como parâmetro e retorna True se for um palíndromo (uma palavra que é igual se lida da esquerda para a direita e vice-versa) e False caso contrário.

In [12]:
def verificar_palindromo(texto):
  texto_limpo = texto.replace(" ", "").lower()
  return texto_limpo == texto_limpo[::-1]  

print(verificar_palindromo("Ana"))          # Saída: True
print(verificar_palindromo("python"))       # Saída: False

True
False

##Desafio listas e funções:

Crie uma função que representa o jogo batalha naval.

Dentro da função crie uma estrutura bidimensional utilizando listas com sublistas para representar um tabuleiro (1 lista com 20 elementos e cada elemento é uma lista de 20 elementos, tabuleiro 20x20). Cada posição irá armazenar 1 valor numérico que significa:
- 0 - Água
- 1 - Navio

Para cada posição escolha esses valores aleatoriamente, respeitando a regra de que não podem existir mais de 20 navios no tabuleiro.

Após os valores serem distribuídos, o programa deve pedir ao usuário uma posição do tabuleiro e informar se ele acertou um navio ou água e repetir o procedimento até que o usuário derrote todos os navios ou chegue ao limite de 35 tentativas.

In [ ]:
import random

navios_colocados = 0

erros = 0
tentativas = 0
navios_atingidos = 0

# Criar o tabuleiro vazio
tabuleiro = [[0] * 20 for _ in range(20)]

# Função para imprimir o tabuleiro
def imprimir_tabuleiro():
    for linha in tabuleiro:
        print(" ".join(str(valor) for valor in linha))
    print()

# Distribuir os navios aleatoriamente
while navios_colocados < 20:
    
    x = random.randint(0, 19)
    y = random.randint(0, 19)
    
    if tabuleiro[x][y] == 0:
        tabuleiro[x][y] = 1
        navios_colocados += 1

while tentativas < 35 and navios_atingidos < 20:
    print(f"Tentativa {tentativas + 1}")
    
    x = int(input("Digite a linha (0-19): "))
    y = int(input("Digite a coluna (0-19): "))
    
    if 0 <= x < 20 and 0 <= y < 20:
        if tabuleiro[x][y] == 1:
            print("Parabéns! Você acertou um navio!")
            tabuleiro[x][y] = '1'
            navios_atingidos += 1
        else:
            print("Água. Tente novamente.")
            # tabuleiro[x][y] = '0' 
            erros += 1
    else:
        print("Posição inválida. Tente novamente.")
    imprimir_tabuleiro()
    tentativas += 1

# Verificar se o jogador ganhou ou perdeu
if navios_atingidos == 20:
    print("Parabéns! Você derrotou todos os navios!")
else:
    print(f"Fim do jogo! Você acertou {navios_atingidos} navios, errou {erros} vezes, e usou {tentativas} tentativas.")

Modifique o programa anterior para exibir as seguintes estatísticas.
- Acertos em água
- Acertos em Navios
- Porcentagem de acertos em água
- Porcentagem de acertos em Navios
- Acertos ininterruptos (maior quantidade de acertos em sequência)

In [ ]:
import random

navios_colocados = 0
tentativas = 0
navios_atingidos = 0
acertos_agua = 0
acertos_navios = 0
acertos_ininterruptos = 0
acertos_atuais = 0

# Criar o tabuleiro vazio
tabuleiro = [[0] * 20 for _ in range(20)]

# Função para imprimir o tabuleiro
def imprimir_tabuleiro():
    for linha in tabuleiro:
        print(" ".join(str(valor) for valor in linha))
    print()

# Distribuir os navios aleatoriamente
while navios_colocados < 20:
    x = random.randint(0, 19)
    y = random.randint(0, 19)
    if tabuleiro[x][y] == 0:
        tabuleiro[x][y] = 1
        navios_colocados += 1

# Loop principal do jogo
while tentativas < 35 and navios_atingidos < 20:
    print(f"Tentativa {tentativas + 1}")
    x = int(input("Digite a linha (0-19): "))
    y = int(input("Digite a coluna (0-19): "))

    if 0 <= x < 20 and 0 <= y < 20:
        if tabuleiro[x][y] == 1:
            print("Parabéns! Você acertou um navio!")
            tabuleiro[x][y] = '1'  # Marca o navio atingido
            navios_atingidos += 1
            acertos_navios += 1
            acertos_atuais += 1
        else:
            print("Água. Tente novamente.")
            acertos_agua += 1
            acertos_atuais = 0  # Reinicia a sequência de acertos
    else:
        print("Posição inválida. Tente novamente.")

    # Atualiza a maior sequência de acertos
    acertos_ininterruptos = max(acertos_ininterruptos, acertos_atuais)

    imprimir_tabuleiro()
    tentativas += 1

# Calcula as porcentagens de acerto
porcentagem_agua = (acertos_agua / tentativas) * 100 if tentativas > 0 else 0
porcentagem_navios = (acertos_navios / tentativas) * 100 if tentativas > 0 else 0

# Resultado final
if navios_atingidos == 20:
    print("Parabéns! Você derrotou todos os navios!")
else:
    print(f"Fim do jogo! Você acertou {navios_atingidos} navios.")

# Exibe as estatísticas
print("\nEstatísticas:")
print(f"Acertos em água: {acertos_agua}")
print(f"Acertos em navios: {acertos_navios}")
print(f"Porcentagem de acertos em água: {porcentagem_agua:.2f}%")
print(f"Porcentagem de acertos em navios: {porcentagem_navios:.2f}%")
print(f"Maior número de acertos ininterruptos: {acertos_ininterruptos}")

#Manipulação de arquivos: Conteudo será trabalhado na aula do

UUtilize o arquivo ‘compras.csv’ como base para resolver os seguintes exercícios.  disponivel em: https://drive.google.com/file/d/1cqqr7kWuBYYJxJ8W_-KHmcZHs6sfV_is/view

Utilize as seguintes faixas etárias nos exercícios em que for necessário.
- Jovens, 18 a 25 anos
- Adultos, 26 a 59 anos
- Idosos, igual ou maior que 60 anos

Func lista

In [15]:
import csv

caminho_arquivo = "/Users/lucaslumertz/Documents/1Programacao/Projetos/Cursos/growdev/dados_para_exercicios/compras.csv"

def ler_csv_para_lista(caminho_arquivo):
    dados = []
    with open(caminho_arquivo, newline='', encoding='utf-8') as csvfile:
        leitor = csv.reader(csvfile)
        cabecalho = next(leitor)
        for linha in leitor:
            dados.append(linha)
    return cabecalho, dados

In [16]:
cabecalho, dados = ler_csv_para_lista(caminho_arquivo)

func dic

In [ ]:
import csv

def ler_csv_para_dicionario(caminho_arquivo):
    dados = {}
    with open(caminho_arquivo, newline='', encoding='utf-8') as csvfile:
        leitor = csv.reader(csvfile)
        cabecalho = next(leitor)  # Lê a linha de cabeçalho

        for i, linha in enumerate(leitor):
            individuo = {cabecalho[j]: linha[j] for j in range(len(cabecalho))}
            dados[i] = individuo

    return dados

In [ ]:
dados_dicionario = ler_csv_para_dicionario('/compras.csv')

In [ ]:
import pprint

In [ ]:
pprint.pprint(dados_dicionario)

A saída de streaming foi truncada nas últimas 5000 linhas.
        'sexo': 'M',
        'sobrenome': 'Gomes'},
 4286: {'ano': '2005',
        'compra': '1074',
        'idade': '68',
        'nome': 'Heitor',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Ferreira'},
 4287: {'ano': '2009',
        'compra': '8103',
        'idade': '37',
        'nome': 'Maria',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4288: {'ano': '2006',
        'compra': '6723',
        'idade': '23',
        'nome': 'Alice',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Ribeiro'},
 4289: {'ano': '2020',
        'compra': '2214',
        'idade': '46',
        'nome': 'Maria',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Silva'},
 4290: {'ano': '2018',
        'compra': '2758',
        'idade': '37',
        'nome': 'Davi',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4291: {'ano': '2014',
        'compra': '2195',
        'idade': '24',
        'nome': 'Davi',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Gomes'},
 4292: {'ano': '2020',
        'compra': '3507',
        'idade': '34',
        'nome': 'Helena',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Santos'},
 4293: {'ano': '2008',
        'compra': '3132',
        'idade': '25',
        'nome': 'Helena',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Gomes'},
 4294: {'ano': '2020',
        'compra': '5262',
        'idade': '20',
        'nome': 'Maria',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4295: {'ano': '2016',
        'compra': '4120',
        'idade': '21',
        'nome': 'Miguel',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Pereira'},
 4296: {'ano': '2009',
        'compra': '999',
        'idade': '37',
        'nome': 'Valentina',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Ribeiro'},
 4297: {'ano': '2008',
        'compra': '9711',
        'idade': '55',
        'nome': 'Bernardo',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Maia'},
 4298: {'ano': '2019',
        'compra': '2985',
        'idade': '43',
        'nome': 'Gael',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4299: {'ano': '2011',
        'compra': '4177',
        'idade': '25',
        'nome': 'Bernardo',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Gomes'},
 4300: {'ano': '2013',
        'compra': '8771',
        'idade': '46',
        'nome': 'Heloisa',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Oliveira'},
 4301: {'ano': '2007',
        'compra': '4268',
        'idade': '19',
        'nome': 'Gabriel',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Souza'},
 4302: {'ano': '2018',
        'compra': '8591',
        'idade': '63',
        'nome': 'Maria',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Alves'},
 4303: {'ano': '2020',
        'compra': '7674',
        'idade': '33',
        'nome': 'Maria',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Soares'},
 4304: {'ano': '2012',
        'compra': '9626',
        'idade': '59',
        'nome': 'Laura',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Souza'},
 4305: {'ano': '2006',
        'compra': '6798',
        'idade': '19',
        'nome': 'Helena',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Silva'},
 4306: {'ano': '2014',
        'compra': '8294',
        'idade': '59',
        'nome': 'Heloisa',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4307: {'ano': '2018',
        'compra': '5597',
        'idade': '52',
        'nome': 'Theo',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Maia'},
 4308: {'ano': '2008',
        'compra': '3917',
        'idade': '39',
        'nome': 'Alice',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4309: {'ano': '2017',
        'compra': '4457',
        'idade': '26',
        'nome': 'Maria',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4310: {'ano': '2015',
        'compra': '9195',
        'idade': '25',
        'nome': 'Laura',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Rodrigues'},
 4311: {'ano': '2014',
        'compra': '4217',
        'idade': '47',
        'nome': 'Davi',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Pereira'},
 4312: {'ano': '2010',
        'compra': '5700',
        'idade': '25',
        'nome': 'Helena',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Alves'},
 4313: {'ano': '2017',
        'compra': '7257',
        'idade': '49',
        'nome': 'Helena',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4314: {'ano': '2011',
        'compra': '6730',
        'idade': '48',
        'nome': 'Gabriel',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4315: {'ano': '2009',
        'compra': '4824',
        'idade': '50',
        'nome': 'Helena',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Martins'},
 4316: {'ano': '2013',
        'compra': '8809',
        'idade': '50',
        'nome': 'Sophia',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Silva'},
 4317: {'ano': '2010',
        'compra': '2503',
        'idade': '33',
        'nome': 'Helena',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Alves'},
 4318: {'ano': '2020',
        'compra': '1485',
        'idade': '59',
        'nome': 'Gael',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Pereira'},
 4319: {'ano': '2016',
        'compra': '4224',
        'idade': '31',
        'nome': 'Gabriel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4320: {'ano': '2017',
        'compra': '809',
        'idade': '29',
        'nome': 'Valentina',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Soares'},
 4321: {'ano': '2020',
        'compra': '9755',
        'idade': '60',
        'nome': 'Davi',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Santos'},
 4322: {'ano': '2020',
        'compra': '1736',
        'idade': '62',
        'nome': 'Sophia',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Ferreira'},
 4323: {'ano': '2012',
        'compra': '4786',
        'idade': '40',
        'nome': 'Theo',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Maia'},
 4324: {'ano': '2011',
        'compra': '3371',
        'idade': '42',
        'nome': 'Arthur',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4325: {'ano': '2012',
        'compra': '5177',
        'idade': '51',
        'nome': 'Gael',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4326: {'ano': '2013',
        'compra': '1346',
        'idade': '41',
        'nome': 'Bernardo',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Martins'},
 4327: {'ano': '2007',
        'compra': '2855',
        'idade': '39',
        'nome': 'Alice',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4328: {'ano': '2015',
        'compra': '9844',
        'idade': '40',
        'nome': 'Sophia',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4329: {'ano': '2013',
        'compra': '4214',
        'idade': '20',
        'nome': 'Samuel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Ribeiro'},
 4330: {'ano': '2019',
        'compra': '2421',
        'idade': '36',
        'nome': 'Helena',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Gomes'},
 4331: {'ano': '2017',
        'compra': '937',
        'idade': '61',
        'nome': 'Miguel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4332: {'ano': '2011',
        'compra': '3861',
        'idade': '47',
        'nome': 'Heitor',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4333: {'ano': '2014',
        'compra': '4150',
        'idade': '49',
        'nome': 'Helena',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Rodrigues'},
 4334: {'ano': '2020',
        'compra': '9145',
        'idade': '47',
        'nome': 'Valentina',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Soares'},
 4335: {'ano': '2017',
        'compra': '2223',
        'idade': '23',
        'nome': 'Bernardo',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4336: {'ano': '2018',
        'compra': '8853',
        'idade': '65',
        'nome': 'Maria',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Santos'},
 4337: {'ano': '2010',
        'compra': '5568',
        'idade': '18',
        'nome': 'Arthur',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Maia'},
 4338: {'ano': '2008',
        'compra': '529',
        'idade': '27',
        'nome': 'Gabriel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4339: {'ano': '2014',
        'compra': '6180',
        'idade': '55',
        'nome': 'Gabriel',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Gomes'},
 4340: {'ano': '2011',
        'compra': '1341',
        'idade': '27',
        'nome': 'Gabriel',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4341: {'ano': '2006',
        'compra': '8463',
        'idade': '37',
        'nome': 'Samuel',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Ribeiro'},
 4342: {'ano': '2014',
        'compra': '7082',
        'idade': '65',
        'nome': 'Alice',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Souza'},
 4343: {'ano': '2018',
        'compra': '5638',
        'idade': '29',
        'nome': 'Heloisa',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4344: {'ano': '2006',
        'compra': '516',
        'idade': '49',
        'nome': 'Gael',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4345: {'ano': '2005',
        'compra': '9365',
        'idade': '53',
        'nome': 'Heitor',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Pereira'},
 4346: {'ano': '2020',
        'compra': '8407',
        'idade': '41',
        'nome': 'Gael',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Silva'},
 4347: {'ano': '2009',
        'compra': '8467',
        'idade': '23',
        'nome': 'Gabriel',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4348: {'ano': '2020',
        'compra': '9061',
        'idade': '28',
        'nome': 'Heloisa',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Gomes'},
 4349: {'ano': '2011',
        'compra': '1695',
        'idade': '52',
        'nome': 'Helena',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Ferreira'},
 4350: {'ano': '2017',
        'compra': '8471',
        'idade': '66',
        'nome': 'Gabriel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4351: {'ano': '2020',
        'compra': '2746',
        'idade': '65',
        'nome': 'Maria',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Santos'},
 4352: {'ano': '2015',
        'compra': '5715',
        'idade': '61',
        'nome': 'Heloisa',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Silva'},
 4353: {'ano': '2017',
        'compra': '8198',
        'idade': '43',
        'nome': 'Arthur',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4354: {'ano': '2013',
        'compra': '3207',
        'idade': '43',
        'nome': 'Samuel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4355: {'ano': '2013',
        'compra': '3515',
        'idade': '65',
        'nome': 'Alice',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Alves'},
 4356: {'ano': '2006',
        'compra': '3322',
        'idade': '57',
        'nome': 'Maria',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Santos'},
 4357: {'ano': '2020',
        'compra': '3435',
        'idade': '31',
        'nome': 'Alice',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Oliveira'},
 4358: {'ano': '2005',
        'compra': '3495',
        'idade': '35',
        'nome': 'Gael',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4359: {'ano': '2015',
        'compra': '8072',
        'idade': '48',
        'nome': 'Sophia',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Oliveira'},
 4360: {'ano': '2009',
        'compra': '9469',
        'idade': '46',
        'nome': 'Valentina',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Ribeiro'},
 4361: {'ano': '2009',
        'compra': '4570',
        'idade': '51',
        'nome': 'Helena',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4362: {'ano': '2013',
        'compra': '6286',
        'idade': '70',
        'nome': 'Miguel',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Ribeiro'},
 4363: {'ano': '2020',
        'compra': '4734',
        'idade': '42',
        'nome': 'Samuel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Soares'},
 4364: {'ano': '2007',
        'compra': '3129',
        'idade': '44',
        'nome': 'Theo',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Gomes'},
 4365: {'ano': '2013',
        'compra': '6393',
        'idade': '21',
        'nome': 'Maria',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Maia'},
 4366: {'ano': '2019',
        'compra': '5297',
        'idade': '52',
        'nome': 'Heloisa',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4367: {'ano': '2014',
        'compra': '3805',
        'idade': '27',
        'nome': 'Alice',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4368: {'ano': '2007',
        'compra': '1546',
        'idade': '43',
        'nome': 'Maria',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Soares'},
 4369: {'ano': '2011',
        'compra': '2179',
        'idade': '47',
        'nome': 'Gael',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Souza'},
 4370: {'ano': '2016',
        'compra': '5758',
        'idade': '66',
        'nome': 'Heitor',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4371: {'ano': '2011',
        'compra': '724',
        'idade': '46',
        'nome': 'Davi',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Maia'},
 4372: {'ano': '2005',
        'compra': '4803',
        'idade': '49',
        'nome': 'Sophia',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Ferreira'},
 4373: {'ano': '2009',
        'compra': '9724',
        'idade': '32',
        'nome': 'Heloisa',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Santos'},
 4374: {'ano': '2007',
        'compra': '7303',
        'idade': '67',
        'nome': 'Laura',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Alves'},
 4375: {'ano': '2005',
        'compra': '7733',
        'idade': '29',
        'nome': 'Heloisa',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Ribeiro'},
 4376: {'ano': '2012',
        'compra': '9536',
        'idade': '27',
        'nome': 'Gabriel',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Soares'},
 4377: {'ano': '2016',
        'compra': '5905',
        'idade': '31',
        'nome': 'Gael',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4378: {'ano': '2015',
        'compra': '5256',
        'idade': '25',
        'nome': 'Alice',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Pereira'},
 4379: {'ano': '2017',
        'compra': '8451',
        'idade': '41',
        'nome': 'Arthur',
        'pagamento': 'dinheiro',
        'sexo': 'M',
        'sobrenome': 'Ribeiro'},
 4380: {'ano': '2009',
        'compra': '5761',
        'idade': '38',
        'nome': 'Bernardo',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Ferreira'},
 4381: {'ano': '2015',
        'compra': '4360',
        'idade': '31',
        'nome': 'Gael',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Alves'},
 4382: {'ano': '2020',
        'compra': '4964',
        'idade': '44',
        'nome': 'Helena',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Martins'},
 4383: {'ano': '2019',
        'compra': '2717',
        'idade': '55',
        'nome': 'Maria',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Alves'},
 4384: {'ano': '2019',
        'compra': '3608',
        'idade': '54',
        'nome': 'Samuel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Ribeiro'},
 4385: {'ano': '2015',
        'compra': '6664',
        'idade': '66',
        'nome': 'Heloisa',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Soares'},
 4386: {'ano': '2005',
        'compra': '8118',
        'idade': '39',
        'nome': 'Sophia',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Martins'},
 4387: {'ano': '2008',
        'compra': '6212',
        'idade': '64',
        'nome': 'Maria',
        'pagamento': 'credito',
        'sexo': 'F',
        'sobrenome': 'Silva'},
 4388: {'ano': '2007',
        'compra': '3464',
        'idade': '70',
        'nome': 'Bernardo',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Soares'},
 4389: {'ano': '2008',
        'compra': '6888',
        'idade': '37',
        'nome': 'Sophia',
        'pagamento': 'debito',
        'sexo': 'F',
        'sobrenome': 'Ferreira'},
 4390: {'ano': '2013',
        'compra': '619',
        'idade': '70',
        'nome': 'Samuel',
        'pagamento': 'debito',
        'sexo': 'M',
        'sobrenome': 'Gomes'},
 4391: {'ano': '2011',
        'compra': '8381',
        'idade': '44',
        'nome': 'Helena',
        'pagamento': 'dinheiro',
        'sexo': 'F',
        'sobrenome': 'Oliveira'},
 4392: {'ano': '2019',
        'compra': '8388',
        'idade': '35',
        'nome': 'Gael',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Ferreira'},
 4393: {'ano': '2007',
        'compra': '7851',
        'idade': '69',
        'nome': 'Miguel',
        'pagamento': 'credito',
        'sexo': 'M',
        'sobrenome': 'Rodrigues'},
 4394: {'ano': '2008',
        'compra': '6049',
        'idade': '51',
        'nome': 'Davi',
        'pagamento': 'debito',

Procure quem foi a pessoa que mais gastou?

Com dic

In [ ]:
def encontrar_maior_gasto(dados):
    maior_gasto = 0
    pessoa_maior_gasto = None

    for individuo, info in dados.items():
        gasto = float(info['compra'])
        if gasto > maior_gasto:
            maior_gasto = gasto
            pessoa_maior_gasto = info
    return pessoa_maior_gasto

In [ ]:
encontrar_maior_gasto(dados_dicionario)

{'nome': 'Gabriel',
 'sobrenome': 'Pereira',
 'idade': '67',
 'sexo': 'M',
 'compra': '9998',
 'ano': '2016',
 'pagamento': 'debito'}

Com lista

In [ ]:
def encontrar_maior_gasto_lista(cabecalho, dados):
    indice_compra = cabecalho.index('compra')
    maior_gasto = 0
    pessoa_maior_gasto = None

    for linha in dados:
        gasto = float(linha[indice_compra])
        if gasto > maior_gasto:
            maior_gasto = gasto
            pessoa_maior_gasto = linha

    pessoa_info = {cabecalho[i]: pessoa_maior_gasto[i] for i in range(len(cabecalho))}
    return pessoa_info

In [ ]:
encontrar_maior_gasto_lista(cabecalho, dados)

{'nome': 'Gabriel',
 'sobrenome': 'Pereira',
 'idade': '67',
 'sexo': 'M',
 'compra': '9998',
 'ano': '2016',
 'pagamento': 'debito'}

Diretório do arquivo:

In [6]:
diretorio = "/Users/lucaslumertz/Documents/1Programacao/Projetos/Cursos/growdev/dados_para_exercicios/compras.csv"

Busque quais são os anos da base de dados?

In [26]:
import csv

def extrair_anos_unicos(nome_arquivo=diretorio, nome_coluna="ano"):
    anos = set() 

    with open(nome_arquivo, 'r', newline='') as arquivo_csv:
        leitor_csv = csv.DictReader(arquivo_csv)  
        for linha in leitor_csv:
            try:
                ano = int(linha[nome_coluna]) 
                anos.add(ano) 
            except (ValueError, KeyError):
                pass  

    return sorted(list(anos))  

anos_unicos = extrair_anos_unicos()
print(anos_unicos)

[2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

Qual a porcentagem de homens e mulheres na base de dados?

In [28]:
import csv

def calcular_porcentagem_sexos(nome_arquivo=diretorio, nome_coluna="sexo"):
    contagem = {"M": 0, "F": 0} 
    total_linhas_validas = 0

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                sexo = linha.get(nome_coluna)  
                if sexo in contagem:  
                    contagem[sexo] += 1
                    total_linhas_validas += 1
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return {"Masculino": 0, "Feminino": 0}

    porcentagens = {}
    for sexo, quantidade in contagem.items():
        porcentagem = (quantidade / total_linhas_validas) * 100 if total_linhas_validas > 0 else 0
        porcentagens[sexo if sexo == "M" else "Feminino"] = round(porcentagem, 2) 

    return porcentagens

porcentagens_sexo = calcular_porcentagem_sexos()
print(porcentagens_sexo)

Qual foi o gasto por ano?

In [30]:
import csv

def calcular_gasto_por_ano(nome_arquivo=diretorio, nome_coluna_ano="ano", nome_coluna_valor="compra"):
    gastos_por_ano = {}

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    ano = int(linha[nome_coluna_ano])
                    valor = float(linha[nome_coluna_valor])
                    gastos_por_ano[ano] = gastos_por_ano.get(ano, 0) + valor
                except (ValueError, KeyError):
                    pass 
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return {} 

    return gastos_por_ano

gastos = calcular_gasto_por_ano()
print(gastos)

{2006: 1671499.0, 2005: 1542645.0, 2010: 1611940.0, 2007: 1711268.0, 2018: 1778911.0, 2019: 1717606.0, 2008: 1475291.0, 2009: 1518779.0, 2015: 1514146.0, 2011: 1668563.0, 2012: 1642695.0, 2017: 1645386.0, 2016: 1812226.0, 2014: 1671750.0, 2020: 1515322.0, 2013: 1647590.0}

Qual foi o ano com maior gasto?

In [31]:
def encontrar_ano_maior_gasto(gastos_por_ano):
    if not gastos_por_ano:
        return None, None

    ano_maior_gasto = max(gastos_por_ano, key=gastos_por_ano.get)
    maior_gasto = gastos_por_ano[ano_maior_gasto]
    return ano_maior_gasto, maior_gasto

gastos = calcular_gasto_por_ano()

ano_maior, valor_maior = encontrar_ano_maior_gasto(gastos)
if ano_maior is not None:
    print(f"O ano com maior gasto foi {ano_maior}, com um total de R$ {valor_maior:.2f}")
else:
    print("Não foi possível calcular os gastos. Verifique o arquivo e tente novamente.")

O ano com maior gasto foi 2016, com um total de R$ 1812226.00

Utilizando as faixas etárias, diga quantas pessoas há em cada faixa?

In [32]:
import csv

def contar_pessoas_por_faixa_etaria(nome_arquivo=diretorio, nome_coluna_idade="idade", jovem_max=25, adulto_max=59):
    contagem_faixas = {'Jovens': 0, 'Adultos': 0, 'Idosos': 0}

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    idade = int(linha[nome_coluna_idade])
                    if idade <= jovem_max:
                        contagem_faixas['Jovens'] += 1
                    elif idade <= adulto_max:
                        contagem_faixas['Adultos'] += 1
                    else:
                        contagem_faixas['Idosos'] += 1
                except (ValueError, KeyError):
                    pass  
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return {}

    return contagem_faixas

contagem = contar_pessoas_por_faixa_etaria()
print(contagem)

{'Jovens': 728, 'Adultos': 3280, 'Idosos': 992}

Qual é a faixa etária que mais gasta?

In [34]:
import csv

def faixa_etaria_que_mais_gasta(nome_arquivo=diretorio, nome_coluna_idade="idade", nome_coluna_valor="compra", jovem_max=25, adulto_max=59):
    gastos_por_faixa = {'Jovens': 0, 'Adultos': 0, 'Idosos': 0}

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    idade = int(linha[nome_coluna_idade])
                    valor = float(linha[nome_coluna_valor])

                    if idade <= jovem_max:
                        gastos_por_faixa['Jovens'] += valor
                    elif idade <= adulto_max:
                        gastos_por_faixa['Adultos'] += valor
                    else:
                        gastos_por_faixa['Idosos'] += valor
                except (ValueError, KeyError):
                    pass  
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return None  

    faixa_maior_gasto = max(gastos_por_faixa, key=gastos_por_faixa.get)
    return faixa_maior_gasto

faixa_etaria = faixa_etaria_que_mais_gasta()
if faixa_etaria:
    print(f"A faixa etária que mais gasta é: {faixa_etaria}")

A faixa etária que mais gasta é: Adultos

A opção de débito é mais utilizada entre homens ou mulheres?

In [9]:
import csv

def debito_mais_usado_por_sexo(nome_arquivo=diretorio, nome_coluna_sexo="sexo", nome_coluna_pagamento="pagamento"):
    contagem_pagamentos = {"Masculino": 0, "Feminino": 0}

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    sexo = linha[nome_coluna_sexo]
                    pagamento = linha[nome_coluna_pagamento]

                    if pagamento == "débito" and sexo in contagem_pagamentos:
                        contagem_pagamentos[sexo] += 1
                except KeyError:
                    pass 
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return None

    sexo_com_mais_debitos = max(contagem_pagamentos, key=contagem_pagamentos.get)
    if contagem_pagamentos["Masculino"] == contagem_pagamentos["Feminino"]:
        return "Igual entre ambos"
    else:
        return sexo_com_mais_debitos

resultado = debito_mais_usado_por_sexo()
if resultado:
    print(f"O sexo que mais utiliza débito é: {resultado}")

O sexo que mais utiliza débito é: Igual entre ambos

Qual o sobrenome que mais aparece na base de dados?

In [10]:
import csv
from collections import Counter

def sobrenome_mais_frequente(nome_arquivo=diretorio, nome_coluna_sobrenome="sobrenome"):
    sobrenomes = []
    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    sobrenome = linha[nome_coluna_sobrenome]
                    sobrenomes.append(sobrenome)
                except KeyError:
                    pass 
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return None

    contagem_sobrenomes = Counter(sobrenomes)

    sobrenome_mais_frequente = contagem_sobrenomes.most_common(1)[0][0]
    return sobrenome_mais_frequente

resultado = sobrenome_mais_frequente()
if resultado:
    print("O sobrenome mais frequente é:", resultado)

O sobrenome mais frequente é: Alves

Qual foi o ano em que os homens mais usaram o crédito?

In [19]:
import csv
from collections import defaultdict

def ano_mais_credito_homens(nome_arquivo=diretorio, nome_coluna_sexo="sexo", nome_coluna_ano="ano", nome_coluna_pagamento="pagamento"):
    contagem_credito_por_ano = defaultdict(int)  
    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    sexo = linha[nome_coluna_sexo]
                    ano = int(linha[nome_coluna_ano])
                    pagamento = linha[nome_coluna_pagamento]

                    if sexo == "M" and pagamento == "credito":
                        contagem_credito_por_ano[ano] += 1
                except (KeyError, ValueError):
                    pass  
    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return None

    ano_maximo = max(contagem_credito_por_ano, key=contagem_credito_por_ano.get, default=None)
    return ano_maximo

resultado = ano_mais_credito_homens()

if resultado:
    print(f"O ano em que os homens mais usaram crédito foi: {resultado}")

O ano em que os homens mais usaram crédito foi: 2018

Qual opção de pagamento é mais utilizada em cada faixa etária?

In [21]:
import csv
from collections import defaultdict

def pagamento_mais_usado_por_faixa_etaria(nome_arquivo=diretorio, nome_coluna_idade="idade", nome_coluna_pagamento="pagamento"):
    contagem_pagamentos = {
        "Jovens": defaultdict(int),
        "Adultos": defaultdict(int),
        "Idosos": defaultdict(int)
    }

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    idade = int(linha[nome_coluna_idade])
                    pagamento = linha[nome_coluna_pagamento].strip().lower()

                    if 18 <= idade <= 25:
                        contagem_pagamentos["Jovens"][pagamento] += 1
                    elif 26 <= idade <= 59:
                        contagem_pagamentos["Adultos"][pagamento] += 1
                    elif idade >= 60:
                        contagem_pagamentos["Idosos"][pagamento] += 1
                except (KeyError, ValueError):
                    continue 

        resultado = {}
        for faixa_etaria, pagamentos in contagem_pagamentos.items():
            if pagamentos:  
                pagamento_mais_usado = max(pagamentos, key=pagamentos.get)
                resultado[faixa_etaria] = pagamento_mais_usado
            else:
                resultado[faixa_etaria] = None  

        return resultado

    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return None

resultado = pagamento_mais_usado_por_faixa_etaria()
if resultado:
    for faixa_etaria, pagamento in resultado.items():
        if pagamento:
            print(f"A opção de pagamento mais usada por {faixa_etaria} é: {pagamento}")
        else:
            print(f"Não foram encontrados dados de compras para {faixa_etaria}.")

A opção de pagamento mais usada por Jovens é: dinheiro
A opção de pagamento mais usada por Adultos é: debito
A opção de pagamento mais usada por Idosos é: debito

Qual o valor gasto em compras por jovens do ano de 2010 até 2015?

In [24]:
import csv

def valor_gasto_jovens(nome_arquivo=diretorio, nome_coluna_idade="idade", nome_coluna_compra="compra", nome_coluna_ano="ano", ano_inicial=None, ano_final=None):
    total_gasto = 0

    try:
        with open(nome_arquivo, 'r', newline='') as arquivo_csv:
            leitor_csv = csv.DictReader(arquivo_csv)
            for linha in leitor_csv:
                try:
                    idade = int(linha[nome_coluna_idade])
                    valor_compra = float(linha[nome_coluna_compra])
                    ano_compra = int(linha[nome_coluna_ano])

                    if 18 <= idade <= 25 and (ano_inicial is None or ano_compra >= ano_inicial) and (ano_final is None or ano_compra <= ano_final):
                        total_gasto += valor_compra
                except (KeyError, ValueError):
                    continue 

        return total_gasto

    except FileNotFoundError:
        print(f"Erro: Arquivo '{nome_arquivo}' não encontrado.")
        return None

valor_total = valor_gasto_jovens(ano_inicial=2010, ano_final=2015) 
if valor_total is not None:
    print(f"O valor total gasto por jovens é: R$ {valor_total:.2f}")

O valor total gasto por jovens é: R$ 1265539.00